name: VS2022

on: push

jobs:
  VS2022-Build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Old method
      id: old_method
      run: echo "::set-output name=option::THIS_ACTUALLY_WORKS"

    - name: New method
      shell: bash
      id: new_method
      run: echo "option=THIS_NO_LONGER_WORKS" >> $GITHUB_OUTPUT

    - name: Build
      shell: cmd
      run: |
        echo "Old method: ${{ steps.old_method.outputs.option }}"
        echo "New method: ${{ steps.new_method.outputs.option }}"
        echo "Well done on introducing a major regression, GitHub!"
